### POST A new Customer

POST http://localhost:8080/api/customers

### POST A new Address

POST http://localhost:8080/api/addresses

### POST A new Company

POST http://localhost:8080/api/companies

### GET All customers

GET http://localhost:8080/api/customers

### GET All addresses

GET http://localhost:8080/api/addresses

### GET All companies

GET http://localhost:8080/api/companies

### GET All published tutorials

GET http://localhost:8080/api/tutorials/published

### GET One Customer

GET http://localhost:8080/api/customers/8

### GET One Company

GET http://localhost:8080/api/addresses/5

### GET One Company

GET http://localhost:8080/api/companies/1


### PUT One tutorial

PUT http://localhost:8080/api/tutorials/:id

### GET filtered tutorials

GET http://localhost:8080/api/tutorials?title=titre

### DELETE one tutorial

DELETE http://localhost:8080/api/tutorials/:id

